kind: ConfigMap
apiVersion: v1
metadata:
  name: app-config-catalog
  namespace: rhdh
  labels:
    app.kubernetes.io/name: backstage
  annotations:
    argocd.argoproj.io/sync-wave: "-1"
data:
  app-config-catalog.yaml: |
    integrations:
      github:
        - host: github.parasol.com
          token: placeholder
          apiBaseUrl: https://github.parasol.com/api/v3
          rawBaseUrl: https://github.parasol.com/raw
    catalog:
      locations:
        - type: url
          target: https://gitlab-gitlab.{{ cluster_subdomain }}/parasol/parasol-entities/blob/main/catalog-index.yaml
          rules:
            - allow: [Component, System, API, Resource, Location, Domain, Group]
