apiVersion: rhdh.redhat.com/v1alpha5
kind: Backstage
metadata:
  name: developer-hub
  namespace: rhdh
spec:
  application:
    appConfig:
      configMaps:
        - name: app-config-rhdh
        - name: app-config-auth
    extraEnvs:
      envs:
        # For illustrative purposes only! We're disabling TLS verification
        # to avoid issues with self-signed certificates used in this lab 
        - name: NODE_TLS_REJECT_UNAUTHORIZED
          value: "0"
      secrets:
        - name: gitlab-token
        - name: argocd-password
        - name: kubernetes-sa-token
        - name: oauth-client
        - name: backend-secret
        - name: mcp-secret
