apiVersion: rhdh.redhat.com/v1alpha5
kind: Backstage
metadata:
  name: developer-hub
  namespace: rhdh
spec:
  application:
    extraEnvs:
      envs:
        - name: NODE_TLS_REJECT_UNAUTHORIZED
          value: "0"
      secrets:
        - name: gitlab-token
        - name: argocd-password
        - name: kubernetes-sa-token
        - name: oauth-client
        - name: backend-secret
