kind: ConfigMap
apiVersion: v1
metadata:
  name: app-config-lightspeed
  namespace: rhdh
  labels:
    app.kubernetes.io/name: backstage
  annotations:
    argocd.argoproj.io/sync-wave: "-1"
data:
  app-config-lightspeed.yaml: |
    lightspeed:
      prompts:
        - title: Using Lightspeed and MCP
          message: Tell me about the parasol-insurance-api API in the Catalog, and write a sample snippet of Java code to access it.
      mcpServers:
      - name: mcp::backstage
        token: ${BACKEND_SECRET}

    backend:
      actions:
        pluginSources:
          - software-catalog-mcp-tool
          - techdocs-mcp-tool
      csp:
        upgrade-insecure-requests: false
        img-src:
          - "'self'"
          - "data:"
          - https://img.freepik.com
          - https://cdn.dribbble.com
          - https://avatars.githubusercontent.com
          - https://api.dicebear.com
        script-src:
          - "'self'"
          - "'unsafe-eval'"
          - https://cdn.jsdelivr.net
