apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: argocd-password
  namespace: rhdh
  labels:
    app.kubernetes.io/name: backstage
  annotations:
    argocd.argoproj.io/sync-wave: "-1"
spec:
  refreshInterval: 5m
  secretStoreRef:
    name: vault-secret-store
    kind: ClusterSecretStore
  target:
    name: argocd-password
    creationPolicy: Owner
  data:
    - secretKey: ARGOCD_OPENSHIFT_GITOPS_PASSWORD
      remoteRef:
        key: secrets/openshift-gitops/admin-password
        property: value
    - secretKey: ARGOCD_RHDH_GITOPS_PASSWORD
      remoteRef:
        key: secrets/rhdh/argocd-password
        property: value
