apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../base
  - es-argocd-password.yaml
  - es-backend-secret.yaml
  - es-gitlab-token.yaml
  - es-kubernetes-sa-token.yaml
  - es-oauth-client.yaml
  - pvc-dynamic-plugins.yaml
  - secret-backstage-npmrc.yaml

patches:
  - path: patches/backstage-cr.yaml
  - path: patches/app-config.yaml
  - path: patches/dynamic-plugins.yaml
