kind: ConfigMap
apiVersion: v1
metadata:
  name: app-config-rhdh
  namespace: rhdh
  labels:
    app.kubernetes.io/name: backstage
  annotations:
    argocd.argoproj.io/sync-wave: "-1"
data:
  # This is a standard Backstage configuration file. It's used to configure the
  # core Backstage application and pass additional plugin configuration.
  app-config-rhdh.yaml: |
    app:
      title: Red Hat Developer Hub
      baseUrl: https://backstage-developer-hub-rhdh.{{ cluster_subdomain }}

    backend:
      baseUrl: https://backstage-developer-hub-rhdh.{{ cluster_subdomain }}
      listen:
        port: 7007
        host: 0.0.0.0

    # This is a development and testing authentication configuration. You'll
    # replace this with a production-ready SSO provider in subsequent modules
    auth:
      environment: development
      providers:
        guest:
          dangerouslyAllowOutsideDevelopment: true
