kind: ConfigMap
apiVersion: v1
metadata:
  name: app-config-catalog
  namespace: rhdh
  labels:
    app.kubernetes.io/name: backstage
  annotations:
    argocd.argoproj.io/sync-wave: "-1"
data:
  app-config-catalog.yaml: |
    catalog:
      locations:
        - type: url
          target: https://gitlab-gitlab.{{ cluster_subdomain }}/parasol/parasol-store/blob/main/catalog-info.yaml
          rules:
            - allow: [Component, System, API, Resource, Location, Domain]
        - type: url
          target: https://gitlab-gitlab.{{ cluster_subdomain }}/parasol/parasol-store-api/blob/main/catalog-info.yaml
          rules:
            - allow: [Component, System, API, Resource, Location, Domain]
        - type: url
          target: https://gitlab-gitlab.{{ cluster_subdomain }}/rhdh/rhdh-template-developer-self-service/blob/main/catalog-info.yaml
          rules:
            - allow: [Template]
